name: karabo_dev_env_GPU
channels:
  - i4ds
  - i4ds/label/dev
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - oskarpy=2.8.dev3
  - rascil=0.7.0
  - xarray=2022.3.0 # Issue https://github.com/i4Ds/Karabo-Pipeline/issues/146
  - astropy
  - numpy>=1.21
  - dask
  - matplotlib
  - healpy
  - requests
  - astropy
  - pinocchio # [linux]
  - katbeam
  - cuda-toolkit
  - ska-gridder-nifty-cuda=0.0.11 # Depends on cuda-toolkit
