name: Build Docs

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Create Environment
        shell: bash -l {0}
        run: |
          conda env create -f environment-dev.yaml
          conda activate karabo_dev_env
          conda install -c conda-forge -y --file doc/doc_packages.txt
      - name: Build Docs
        shell: bash -l {0}
        run: |
          sphinx-apidoc . -o doc/src
          make html
      - name: Archive doc build
        uses: actions/upload-artifact@v3
        with:
          name: docs_built
          path: build/
      - name: Commit built-doc
        run: |
          git config --global user.name 'PaperBot'
          git config --global user.email 'actions@github.com'
          git fetch origin
          git switch pages_source
          
          echo "remove old files"
          find . -maxdepth 1 -type f -delete
          rm -rf _images
          rm -rf _sources
          rm -rf _static
          rm -rf examples
          
          echo "add new files"
          mv build/html/* .
          rm -rf build/
          touch .nojekyll
          
          git add .
          git commit -m "update docs"
          git push
