name: Build Docs

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Create Environment
        shell: bash -l {0}
        run: |
          conda env create -f environment-dev.yaml
          conda activate karabo_dev_env
          conda install -c conda-forge -y --file doc/doc_packages.txt
      - name: Build Docs
        shell: bash -l {0}
        run: |
          conda activate karabo_dev_env
          sphinx-apidoc doc -o _build
          make html
      - name: Archive doc build
        uses: actions/upload-artifact@v3
        with:
          name: docs_built
          path: _build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
